MD_PATH = "/home/s4425412/data/Honours/MD"

SINGLE_PLOT_WIDTH = 9
SINGLE_PLOT_HEIGHT = 7
SINGLE_PLOT_LEG_WIDTH = 9
SINGLE_PLOT_LEG_HEIGHT = 10
FOUR_PLOTS_WIDTH = 10
FOUR_PLOTS_HEIGHT = 8
SIX_PLOTS_WIDTH = 10
SIX_PLOTS_HEIGHT = 12
SIX_PLOTS_HORIZONTAL_WIDTH = 12
SIX_PLOTS_HORIZONTAL_HEIGHT = 7

inhibitor_list = [1, 3, 4, 5, 7, 9]
