MD_PATH = "/home/s4425412/data/Honours/MD"

SINGLE_PLOT_WIDTH, SINGLE_PLOT_HEIGHT = 9, 7
SINGLE_PLOT_LEG_WIDTH, SINGLE_PLOT_LEG_HEIGHT = 9, 10
FOUR_PLOTS_WIDTH, FOUR_PLOTS_HEIGHT = 10, 8
SIX_PLOTS_WIDTH, SIX_PLOTS_HEIGHT = 10, 12
SIX_PLOTS_HORIZONTAL_WIDTH, SIX_PLOTS_HORIZONTAL_HEIGHT = 12, 7

inhibitor_list = [1, 3, 4, 5, 7, 9]
